///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String jpgSwitch0 = 'assets/jpg/switch_0.jpg';
  static const String jpgSwitch1 = 'assets/jpg/switch_1.jpg';
  static const String jpgSwitch2 = 'assets/jpg/switch_2.jpg';
  static const String jpgSwitchBox = 'assets/jpg/switch_box.jpg';
  static const String pngAlexa = 'assets/png/alexa.png';
  static const String pngBeats = 'assets/png/beats.png';
  static const String pngDrone = 'assets/png/drone.png';
  static const String pngGoogle = 'assets/png/google.png';
  static const String pngIphone = 'assets/png/iphone.png';
  static const String pngMac = 'assets/png/mac.png';
  static const String pngPs5 = 'assets/png/ps5.png';
  static const String pngSellar = 'assets/png/sellar.png';
  static const String pngSwitch = 'assets/png/switch.png';
  static const String pngSwitchLogo = 'assets/png/switch_logo.png';
  static const String pngWatch = 'assets/png/watch.png';

}
